### PR TITLE
fix: improve selector for sc-mc renderer

### LINKED ISSUE #2808: after saving scmc-exercise with editor, anwers are misaligned
grafik

expected: alignment as before

link: https://de.serlo-staging.dev/mathe/66811/66811

### PR DESCRIPTION
**Pull request by Entkenntnis**
arbitrary selectors are a blessing and a curse at the same time

### CODE REVIEW

File: src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx [hunk 1]
```diff
@@ -77,7 +77,7 @@ export function ScMcExerciseRenderer({
                   />
                   <label
                     className={clsx(
-                      'serlo-spacing-fix flex cursor-pointer items-center [&>div>*]:ml-2',
+                      'serlo-spacing-fix flex cursor-pointer items-center [&_.slate-container]:mb-0 [&_.slate-p]:ml-2',
```
Comment (elbotho) [inline src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx]: Do you want to have this here or should we try to fix it in `serlo-spacing-fix` where it worked before?

Comment (elbotho) [reply src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx]: in `serlo-tailwind.css`

Comment (Entkenntnis) [reply src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx]: Actually a good point. It could be that the newly inserted `div` is causing more spacing issues, but I haven't tested for it yet.

I'd be fine with leaving the fixes here, because it's very specific to the renderer

Comment (Entkenntnis) [reply src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx]: Ah, I see that you have added `.serlo-spacing-fix` specifically for this place.

Gut feeling: using specific fixes like in this PR is slightly more understandable.

Todo: also update mc exercise

File: src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx [hunk 2]
```diff
@@ -77,7 +77,8 @@ export function ScMcExerciseRenderer({
                   />
                   <label
                     className={clsx(
-                      'serlo-spacing-fix flex cursor-pointer items-center [&>div>*]:ml-2',
+                      /* we override some styles in the answer content because it's not standalone */
```
Comment (elbotho) [inline src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx]: thanks for commenting this.
tbh. I don't really understand what you mean by 
> because it's not standalone

**Review by elbotho — APPROVED** [review]

File: src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx (hunk 2 above)
Comment (Entkenntnis) [reply src/serlo-editor/plugins/sc-mc-exercise/renderer.tsx]: improved comment
