### PR TITLE
math fixes

### LINKED ISSUE #1004: Respect displaystyle in inline-math
While converting latex, don't remove displaystyle if it has been added by the user.

Example Use Case: G_f_t in https://frontend.serlo.org/mathe/2589/2589

Notes: check compatibility with \sf, probably make sanitize-latex context-sensitive.

### LINKED ISSUE #1006: latex sanitize: Handle \sf for aligned environment
This environment is missing from envTag handling.

### PR DESCRIPTION
**Pull request by Entkenntnis**
TODO: After deployment, notify authors in community chat

### CODE REVIEW

File: src/schema/article-renderer.tsx [hunk 1]
```diff
@@ -207,13 +207,20 @@ function renderElement(props: RenderElementProps): React.ReactNode {
   }
   if (element.type === 'math') {
     const nowrap = /\\begin *{(array|aligned)}/.test(element.formula)
+    const addDisplaystile = !/\\displaystyle[^a-z]/.test(element.formula)
```
Comment (Entkenntnis) [inline src/schema/article-renderer.tsx:210]: todo: this regex looks wrong

Comment (Entkenntnis) [reply src/schema/article-renderer.tsx:210]: nah, it's fine
