### PR TITLE
Fix close button position in modal

### LINKED ISSUE #3094: regression: close button placed incorrectly
changes [in this PR](https://github.com/serlo/frontend/pull/3000/) broke the other modals with close buttons:

e.g:
image

### PR DESCRIPTION
**Pull request by CodingDive**
I did not check all the modals (there are a lot). But I added back the absolute position.

Fixes #3094

### CODE REVIEW

File: src/components/modal-with-close-button.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export function ModalWithCloseButton({
             onClick={onRequestClose}
             title={strings.share.close}
             dataQa="modal-close-button"
-            className={closeButtonClassName}
+            className={clsx('absolute right-2 top-2', closeButtonClassName)}
```
Comment (elbotho) [inline src/components/modal-with-close-button.tsx]:
```suggestion
            className={clsx('absolute right-3.5 top-3.5', closeButtonClassName)}
```
that was the old value

**Review by elbotho — CHANGES_REQUESTED** [review]

**Review by elbotho — APPROVED** [review]
thanks!
