### PR TITLE
fix/selection menu improvements

### LINKED ISSUE #2388: editor: selection menu improvements
### small bugs/problems

- [x] add text plugin as first plugin (activating it just removes the `/`)
- [x] Hover (mouse) and focused (arrow keys) entries both are visually prominent and can be at the same time. Solution: only one should be visible at the same time (hide other focus when hovering with mouse or manage in state)

### wish (optional)
- remove `/` when closing the popover or deselecting the text-plugin

### PR DESCRIPTION
**Pull request by hejtful**
resolves https://github.com/serlo/frontend/issues/2388

### CODE REVIEW

File: src/serlo-editor-repo/plugin-text/components/text-editor.tsx [hunk 1]
```diff
@@ -98,17 +96,23 @@ export function TextEditor(props: TextEditorProps) {
...
   useEffect(() => {
-    // If the editor is not focused, do nothing
-    if (focused === false) return
+    // Get the current text value of the editor
+    const text = Node.string(editor)
+
+    // If the editor is not focused, remove the suggestions search
+    // and exit the useEffect hook
+    if (focused === false) {
+      if (text.startsWith('/')) {
```
Comment (elbotho) [inline src/serlo-editor-repo/plugin-text/components/text-editor.tsx:105]: Is it possible to check if the popover is still open at this point?
Currently this would always remove a line like `// this is how a comment looks like`.
Def. an edge case but maybe there are more cases like this (not sure).

Fallback: Check if whitespaces are in text and then return.

**Review by elbotho — APPROVED** [review]
One question/request. Rest looks great 👍

File: src/serlo-editor-repo/plugin-text/components/text-editor.tsx (hunk 1 above)
Comment (hejtful) [reply src/serlo-editor-repo/plugin-text/components/text-editor.tsx:105]: > Is it possible to check if the popover is still open at this point?

The popover will be closed at this point, because it's only open when `focused === true`.

This logic will change, however. I'll open an issue for that now.
