### PR TITLE
handle empty value in plugin-text deserialization

### LINKED ISSUE #2411: editor: crash on certain articles
example: https://de.serlo.org/nachhaltigkeit/270596/veganerin-werden-wie-fange-ich-an

there are errors in the console

### PR DESCRIPTION
**Pull request by Entkenntnis**
The debugging shows that `value` can be  `[]`. Now the deserializer handles this case and it fixes the bug.

example: https://frontend-git-2411-editor-crash-on-certain-articles-serlo.vercel.app//entity/repository/add-revision/270596/270598

### CODE REVIEW

File: src/serlo-editor-repo/plugin-text/index.tsx [hunk 1]
```diff
@@ -35,6 +35,11 @@ const createTextPlugin = (
       return value
     },
     deserialize(value) {
+      // sometimes, the value is empty, e.g. https://github.com/serlo/frontend/issues/2411
```
Comment (hejtful) [inline src/serlo-editor-repo/plugin-text/index.tsx]: I'm not sure how helpful this comment is, as the production link from the issue will be working when this is deployed.

**Review by hejtful — APPROVED** [review]
Minor suggestion, but great work in finding the cause so quickly

File: src/serlo-editor-repo/plugin-text/index.tsx (hunk 1 above)
Comment (Entkenntnis) [reply src/serlo-editor-repo/plugin-text/index.tsx]: true, will probably just remove it
