### PR TITLE
fix(sorting): retrieve preview string from multimedia

### LINKED ISSUE #3364: sorting exercises: show string preview
https://de.serlo.org/taxonomy/term/sort/entities/298184

grafik

The string preview feature is quite useful - and would be nice if it works with multimedia plugins.

### PR DESCRIPTION
**Pull request by Entkenntnis**
example: http://localhost:3000/taxonomy/term/sort/entities/298184

### CODE REVIEW

**Review by hejtful — APPROVED** [review]

File: packages/editor/src/plugins/text/utils/static-extract-text.ts [hunk 1]
```diff
@@ -9,7 +13,19 @@ export function extractDescendant(node: Descendant): string {
...
+  if (
+    document &&
+    isMultimediaDocument(document) &&
+    isRowsDocument(document.state.explanation)
+  ) {
+    return document.state.explanation.state
+      .map(extractStringFromTextDocument)
+      .join(' ')
+      .trim()
+  }
```
Comment (elbotho) [inline packages/editor/src/plugins/text/utils/static-extract-text.ts]: Since this is a helper in a file inside the text plugin and is named `extractStringFromTextDocument` I'd prefer this code to be somewhere else.
Imho. this should be a generic helper in e.g. `/plugin/helpers/static-extract-text-from-document` or something like that.

**Review by elbotho — CHANGES_REQUESTED** [review]

File: packages/editor/src/plugins/text/utils/static-extract-text.ts (hunk 1 above)
Comment (elbotho) [reply packages/editor/src/plugins/text/utils/static-extract-text.ts]: (or inside multimedia plugin)

**Comment by elbotho** [comment]
See comment above, but code seems to work fine, thank you!

File: packages/editor/src/plugins/text/utils/static-extract-text.ts (hunk 1 above)
Comment (Entkenntnis) [reply packages/editor/src/plugins/text/utils/static-extract-text.ts]: I have move the code to the one place it's used.

**Review by elbotho — COMMENTED** [review]
thank you!
