### PR TITLE
fix and simplify highlight plugin

### LINKED ISSUE #2183: editor: enter in hightlight plugin textarea creates new plugin

### PR DESCRIPTION
**Pull request by elbotho**
- closes #2183
- removes styled components
- relies on native styling and cleaner markup

(might look wonky on some OSs/Browsers but works way better and styling overhaul will come soon anyway)

### CODE REVIEW

**Review by Entkenntnis — APPROVED** [review]
Thanks for fixing this! FF/Win10 looks fine

File: src/edtr-io/plugins/highlight/editor.tsx [hunk 1]
```diff
@@ -42,45 +19,23 @@ export function HighlightEditor(props: HighlightProps) {
...
         onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => {
           state.code.set(e.target.value)
         }}
+        // make sure editor does not create new plugin on enter etc
+        onKeyDown={(e) => e.stopPropagation()}
+        className="h-32 w-full m-auto p-side resize-y font-mono shadow-menu border-none"
       >
         {state.code.value}
-      </Textarea>
-      <EditorInlineSettings>
```
Comment (Entkenntnis) [inline src/edtr-io/plugins/highlight/editor.tsx:57]: `EditorInlineSettings` is really just a div with a margin top, nothing more - good to know...

Checked it right now to be sure (https://github.com/edtr-io/edtr-io/blob/d1d3fd8e32c43ed9ec831b230b9147b7b85d54a4/packages/public/editor-ui/src/editor-inline-settings.tsx)

File: src/edtr-io/plugins/highlight/editor.tsx [hunk 2]
```diff
@@ -90,4 +45,42 @@ export function HighlightEditor(props: HighlightProps) {
...
+          <select
+            onChange={(e) => state.language.set(e.target.value)}
+            className="cursor-pointer"
+          >
+            {languages.map((language) => {
+              return (
+                <option
+                  key={language}
+                  value={language}
+                  selected={
```
Comment (Entkenntnis) [inline src/edtr-io/plugins/highlight/editor.tsx]: info, this is the warning I get about selected:

grafik

I don't have a strong opinion here, but with a slight preference to remove the react warning

File: src/edtr-io/plugins/highlight/editor.tsx (hunk 1 above)
Comment (elbotho) [reply src/edtr-io/plugins/highlight/editor.tsx:57]: jup, I was a bit underwhelmed as well ^^

File: src/edtr-io/plugins/highlight/editor.tsx (hunk 2 above)
Comment (elbotho) [reply src/edtr-io/plugins/highlight/editor.tsx]: will change. Where did you catch that?

**Comment by elbotho** [comment]
fixed warning and did some minor tweaks

File: src/edtr-io/plugins/highlight/editor.tsx [hunk 3]
```diff
@@ -37,50 +14,29 @@ export function HighlightEditor(props: HighlightProps) {
     if (!edit) {
       setTimeout(() => {
         setEditThrottled(false)
-      }, 500)
+      }, 100)
```
Comment (elbotho) [inline src/edtr-io/plugins/highlight/editor.tsx:17]: @Entkenntnis do you know why this delay was implemented?
Will shortening it break something? (Feels less buggy with 100ms)

File: src/edtr-io/plugins/highlight/editor.tsx (hunk 2 above)
Comment (Entkenntnis) [reply src/edtr-io/plugins/highlight/editor.tsx]: console of localhost, the first time I visit the page

File: src/edtr-io/plugins/highlight/editor.tsx (hunk 3 above)
Comment (Entkenntnis) [reply src/edtr-io/plugins/highlight/editor.tsx:17]: mellie added it 4 years ago: https://github.com/edtr-io/edtr-io/commit/ec459ce6b843e61eb65ba56337284e126b89f94c

The plugin changed significantly since, currently I don't see anything that could break (react should take care of rendering) - maybe we don't need anymore

Comment (elbotho) [reply src/edtr-io/plugins/highlight/editor.tsx:17]: 👍 then let's try it like this. Maybe I'll ask Mellie if she remembers :)

Comment (elbotho) [reply src/edtr-io/plugins/highlight/editor.tsx:17]: @metzgaria do you by change rememer why this was needed? 😅
