### PR TITLE
fix: enable math elements in blanks exercise

### LINKED ISSUE #3264: editor: can't switch math element mode inside of a fill-in-the-blanks exercise
When clicking on the "latex/visual" select element, it disappears from view

### PR DESCRIPTION
**Pull request by hejtful**
fixes https://github.com/serlo/frontend/issues/3264

### CODE REVIEW

File: packages/editor/src/core/sub-document/editor.tsx [hunk 1]
```diff
@@ -56,7 +56,9 @@ export function SubDocumentEditor({ id, pluginProps }: SubDocumentProps) {
       // we overwrite it here (because it's probably because of tab navigation)
       setTimeout(() => {
         // fixes a bug in table plugin with disappearing buttons
-        if (e.target.nodeName?.toLowerCase() === 'button') return
+        if (['button', 'select'].includes(e.target.nodeName?.toLowerCase())) {
+          return
+        }
```
Comment (hejtful) [inline packages/editor/src/core/sub-document/editor.tsx:61]: @elbotho This is the part that fixes the focus bug. Do you see any potential problems with this change?

Comment (elbotho) [reply packages/editor/src/core/sub-document/editor.tsx:61]: Can't think of an obvious problem.
Let's see if we encounter some and add tests accordingly.

**Review by elbotho — APPROVED** [review]
nice, thank you!
