### PR TITLE
Profile fixes, new TimeBadge

### LINKED ISSUE #1112: User-profiles: Fix layout for long usernames
See https://de.serlo.org/user/91335/daniel-flueck and https://de.serlo.org/user/146133/wandapaetzold in chrome:

image

### LINKED ISSUE #1125: User-Profiles: Improvement from feedback
From the feedback I got:

* [x] Note that the uploaded image need to be quadtratic
* [x] Investigate whether cache updates when profile is edited
* [x] Investigate what happens when new profile pic in rocket chat is uploaded

(ping @simonkoehl so that you get notified when I work on this issue)

### PR DESCRIPTION
**Pull request by elbotho**
We now have space for long usernames and more badges in the future
Also I prototyped a Time Badge to display the "With Serlo since…" info a little bit more attractively.

Now also addresses #1125

### Examples
https://frontend-git-profile-username-fix-serlo.vercel.app/user/profile/wandapaetzold
https://frontend-git-profile-username-fix-serlo.vercel.app/user/profile/kulla

### CODE REVIEW

**Review by kulla — APPROVED** [review]
@elbotho Thx for the improvements. I have added some refactorings. Feel free to merge this PR after having looked into them!

File: src/data/de/index.ts [hunk 1]
```diff
@@ -171,7 +171,6 @@ export const instanceData = {
     },
     profiles: {
       aboutMe: "Über mich",
-      activeSince: "Bei Serlo seit",
```
Comment (elbotho) [inline src/data/de/index.ts:174]: just for reference: changing `en` should be enough. Other files are generated by Crowdin.

File: src/components/pages/user/profile.tsx [hunk 2]
```diff
@@ -243,14 +242,11 @@ export const Profile: NextPage<ProfileProps> = ({ userData }) => {
...
-              .delete('https://community.serlo.org/avatar/botho')
-              .then(function () {
-                void location.reload()
-              })
-          })
+        onClick={async () => {
+          const cache = await caches.open('v1')
+
+          await cache.delete(imageUrl)
+          location.reload()
```
Comment (elbotho) [inline src/components/pages/user/profile.tsx:249]: okay, way nicer 👍 
just copy pasted the `then` stuff to be honest 😅
