### PR TITLE
fix(plugin-text): show static placeholder instead of decorate when config.noLinebreaks

### LINKED ISSUE #2756: optional title placeholder only visible after click
If I create a new box and choose "Merke", the optional title is not visible:

grafik

I can see a text cursor, if I click the plugin, I can see the placeholder:

grafik

Is this a bug or just a glitch? It's a regression because one e2e test fails (so it worked before)

### PR DESCRIPTION
**Pull request by hejtful**
Fixes: https://github.com/serlo/frontend/issues/2756

Test PR: https://github.com/serlo/frontend-e2e-tests/pull/66

### CODE REVIEW

**Review by Entkenntnis — APPROVED** [review]
tested it and it works now

File: src/serlo-editor/plugins/box/editor.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function BoxEditor(props: BoxProps) {
           )}
         >
           <b className="block pb-4">{editorStrings.plugins.box.type}</b>
-          <ul className="unstyled-list pb-8">{renderSettingsLis()}</ul>
+          <ul className="unstyled-list pb-8">{renderSettingsList()}</ul>
```
Comment (elbotho) [inline src/serlo-editor/plugins/box/editor.tsx]: hmm, it's not rendering the list, but the list items. that's why it was `Lis`. If we change this to be more unambiguous I'd go with `renderSettingsListItems` or move the `<ul>` to the render function as well :D

**Review by elbotho — APPROVED** [review]
👍
