### PR TITLE
fix(plugin-image): Show error when image can't be pasted

### LINKED ISSUE #2754: editor(rows/image): no error message when dragging image to upload
when dragging an image-file into the rows plugin:
- upload works: all good, image plugin appears
- upload fails (e.g. filesize error) nothing happens

in the second case we should show an error message as well.

### PR DESCRIPTION
**Pull request by AsterMiha**

### CODE REVIEW

File: src/serlo-editor/plugins/image/index.ts [hunk 1]
```diff
@@ -83,5 +86,5 @@ export type ImageProps = EditorPluginProps<ImagePluginState, ImageConfig>
 
 export interface ImagePluginConfig {
   upload: UploadHandler<string>
-  validate: UploadValidator
+  validate: UploadValidator<Array<{ errorCode: number; message: string }>>
```
Comment (hejtful) [inline src/serlo-editor/plugins/image/index.ts]: There is this [FileError interface](https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/image/image-with-serlo-config.ts#L39) defined already, which you could reuse here. What do you think?

If you do reuse it, please [import it as a type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export), to avoid circular dependency issues.

Comment (AsterMiha) [reply src/serlo-editor/plugins/image/index.ts]: Fixed. Thanks for pointing this out!

**Review by hejtful — APPROVED** [review]

**Review by elbotho — APPROVED** [review]
Thank you, 
interestingly `unauthenticated` error does not show but I think this is unrelated to this PR and not as important.
